# Parameters for control loop
pub_twist_cmd: true
debug_info: false
delay_mode: true
max_speed: 0.5 # unit: m/s 
waypoints_dist: -1.0 # unit: m, set < 0 means computed by node
path_length: 5.0 # unit: m
goal_radius: 0.5 # unit: m
controller_freq: 10
thread_numbers: 4 # Enabling 4 parallel processing threads.

# Parameter for MPC solver
mpc_steps: 20.0
mpc_ref_cte: 0.0
mpc_ref_vel: 0.5
mpc_ref_etheta: 0.0
mpc_w_cte: 100.0
mpc_w_etheta: 0000.0
mpc_w_vel: 1000.0
mpc_w_angvel: 100.0
mpc_w_angvel_d: 0.0
mpc_w_accel: 50.0
mpc_w_accel_d: 0.0
mpc_max_angvel: 1.5 
mpc_max_throttle: 1.0 # Maximal throttle accel
mpc_bound_value: 1.0e3 # Bound value for other variables

# General topic commands
# Except for map_frame all the other following parameters will be prefixed
# by the robot namespace.
global_path_topic: "cmd_global_trajectory" # used to publish the global path.
goal_topic: "cmd_goal" # used to publish the goal.
goal_status_topic: "is_goal_reached" # used to publish the goal status.

# All frames prefixed with namespace except for map.
map_frame: "map" # Won't be namespaced.
odom_frame: "odom"
car_frame: "base_footprint"