obstacle_range: 0.5
raytrace_range: 0.5
# footprint: [[-0.14, -0.14], [-0.14, 0.14], [0.14, 0.14], [0.14, -0.14]]
robot_radius: 0.006
map_topic: /map
subscribe_to_updates: true
global_frame: odom
robot_base_frame: base_link
update_frequency: 30.0
publish_frequency: 30.0
rolling_window: false

plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

static_layer:
  enabled: true
  map_topic: /map
  subscribe_to_updates: false

obstacle_layer:
  enabled: false
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

inflation_layer:
  enabled: true
  inflation_radius: 0.2 # Obstacle wall inflation radius.
  cost_scaling_factor: 5.0 # exponential rate at which the obstacle cost drops off (default: 10)
